[package]
name = "grid-hierarchy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.9" }
bevy-voxel-engine = { path = "bevy-voxel-engine" }
bevy_egui = "0.17"
rand = "0.8"
concurrent-queue = "1.2"
tinyfiledialogs = "3.9"
bevy_mod_debugdump = "0.6"
bevy_obj = "0.9"
