[package]
name = "grid-hierarchy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8"
bevy_egui = "0.15"
bytemuck = "1.10"
rand = "0.8"
dot_vox = "4.1"
wgpu = "0.13.1"
futures-intrusive = "0.4"
concurrent-queue = "1.2"